Repository Crab-Wave/ora, pull requests merged in 2020-05, with the labels that each got.

#35 Basic GUI features
  .gitignore
  ORA.API/Member.cs
  ORA.API/documentation.xml
  ORA.App.GUI.CoreWrapper/ORA.App.GUI.CoreWrapper.csproj
  ORA.App.GUI.CoreWrapper/Program.cs
  ORA.App.GUI/App.xaml
  ORA.App.GUI/App.xaml.cs
  ORA.App.GUI/Assets/crabwave-logo.ico
  ORA.App.GUI/Models/ClusterItem.cs
  ORA.App.GUI/ORA.App.GUI.csproj
  ORA.App.GUI/Program.cs
  ORA.App.GUI/ViewLocator.cs
  ORA.App.GUI/ViewModels/AddClusterItemViewModel.cs
  ORA.App.GUI/ViewModels/HomeViewModel.cs
  ORA.App.GUI/ViewModels/MainWindowViewModel.cs
  ORA.App.GUI/ViewModels/SettingsViewModel.cs
  ORA.App.GUI/ViewModels/ViewModelBase.cs
  ORA.App.GUI/Views/AddClusterItemView.xaml
  ORA.App.GUI/Views/AddClusterItemView.xaml.cs
  ORA.App.GUI/Views/HomeView.xaml
  ORA.App.GUI/Views/HomeView.xaml.cs
  ORA.App.GUI/Views/MainWindow.xaml
  ORA.App.GUI/Views/MainWindow.xaml.cs
  ORA.App.GUI/Views/SettingsView.xaml
  ORA.App.GUI/Views/SettingsView.xaml.cs
  ORA.App.GUI/nuget.config
  ORA.Application.CLI/Clusters.cs
  ORA.Application.CLI/Commands/ManagementCommand.cs
  ORA.Application.CLI/Identities.cs
  ORA.Application.CLI/Objects/UserNameModel.cs
  ORA.Application.CLI/OraApplication.cs
  ORA.Application.CLI/Validators/UserNameValidator.cs
  ORA.Application.Daemon/Program.cs
  ORA.Core/Managers/ClusterManager.cs
  ORA.sln
  build.cake
  build.ps1
  build.sh
Labels: Difficulty: Medium

#36 Remove unused files and namespace commands
  ORA.Application.CLI/CommandManager.cs
  ORA.Application.CLI/Commands/Cluster.cs
  ORA.Application.CLI/Commands/Clusters.cs
  ORA.Application.CLI/Commands/Identities.cs
  ORA.Application.CLI/Commands/Url.cs
  ORA.Application.CLI/ORA.Application.CLI.csproj
  ORA.Application.CLI/Options/Options.cs
  ORA.Application.CLI/Options/Url.cs
  ORA.Application.CLI/OraApplication.cs
Labels: enhancement

#38 Files
  ORA.API/File.cs
  ORA.API/Managers/IAuthManager.cs
  ORA.API/Managers/IClusterManager.cs
  ORA.API/Managers/IFileManager.cs
  ORA.API/Managers/INetworkManager.cs
  ORA.API/Managers/INodeManager.cs
  ORA.API/Network/GenericPacketHandler.cs
  ORA.API/Network/Packet.cs
  ORA.API/Network/PacketHandler.cs
  ORA.API/Network/Packets/FilePacket.cs
  ORA.API/Network/Packets/RequestFilePacket.cs
  ORA.API/Node.cs
  ORA.API/Ora.cs
  ORA.API/Utils/StringProvider.cs
  ORA.API/Utils/StringProviderWithStringArray.cs
  ORA.API/documentation.xml
  ORA.Application.CLI.CoreWrapper/Program.cs
  ORA.Application.CLI/Commands/Url.cs
  ORA.Application.CLI/Program.cs
  ORA.Application.Daemon/Program.cs
  ORA.Core.IPC/Managers/IpcAuthManager.cs
  ORA.Core.IPC/Managers/IpcClusterManager.cs
  ORA.Core.IPC/Managers/IpcFileManager.cs
  ORA.Core.IPC/Managers/IpcNetworkManager.cs
  ORA.Core.IPC/Managers/IpcNodeManager.cs
  ORA.Core.IPC/OraCoreIpc.cs
  ORA.Core/Managers/AuthManager.cs
  ORA.Core/Managers/ClusterManager.cs
  ORA.Core/Managers/FileManager.cs
  ORA.Core/Managers/IdentityManager.cs
  ORA.Core/Managers/NetworkManager.cs
  ORA.Core/Managers/NodeManager.cs
  ORA.Core/ORA.Core.csproj
  ORA.Core/OraCore.cs
  ORA.Core/OraNode.cs
Labels: Difficuly: Hard, Project: API, Project: Core

#39 Fix GetClustersOfUser method
  ORA.Core/Managers/ClusterManager.cs
Labels: bug

#40 Added IsOraTracker method to Ora.cs
  ORA.API/Ora.cs
  ORA.Core.IPC/OraCoreIpc.cs
  ORA.Core/OraCore.cs
Labels: Difficulty: Easy, enhancement
